### ISSUE TITLE
PD-123 Name is missing when the Diagram output to the Canvas

### ISSUE THREAD

**Issue by crapper** [Jerrylum/protocol-diagram#23]
**Describe the bug**
Display wrongly when the Diagram output to the Canvas

**To Reproduce**
Simply type add a field with even length name

**Expected behavior**
The name should be shown in the center of the field of canvas

**Screenshots**
![image](https://github.com/Jerrylum/protocol-diagram/assets/26902835/9f8f8f31-dcaf-4f72-b58c-455e08915446)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 0.0.1

**Comment by Jerrylum** [comment]
Uh, errr, hold on, please help me to investigate and fix the bug. You should push a commit in branch PD-51

**Comment by crapper** [comment]
Furthermore, in here
https://github.com/Jerrylum/protocol-diagram/blob/b5d948df4a399d1507906c56b51f6b09f595fe77/src/diagram/render/Style.ts#L14

A case for handling empty str which can be found as a rowtail is missing

**Comment by crapper** [comment]
The problem should be fixed now by the commit
PD-123 Fix Bug in Diagram Rendering, commit fbc13a2
