### ISSUE TITLE
Bug found about the algorithm of getInsertPositions()

### ISSUE THREAD

**Issue by crapper** [Jerrylum/protocol-diagram#50]
**Describe the bug**
The last Connector has not been treated as Insertable position when left-space-placeholder is true

**To Reproduce**
1. Enable the left-space-placeholder
2. Trigger the onMouseMove of the DragAndDropFieldInteraction
3. Check on the list of potenial insertPositions list 

**Expected behavior**
The character "├" at the last Connector should also included in the return list of getInsertPositions()

**Screenshots**
Normal case:
![image](https://github.com/Jerrylum/protocol-diagram/assets/26902835/34e03a02-9b2e-4f4f-88bc-211ac1dd40a5)
Error case:
![image](https://github.com/Jerrylum/protocol-diagram/assets/26902835/95715fd9-38e8-429d-acd6-c869fe96ef1f)
The insertPositions of the last Connector is missing

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 0.2.0

**Comment by Jerrylum** [comment]
Yea I see, I think we should remove a check for the Connector in the function
